# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "MEI Luoyu"
repository               : "luoyumei1-a/luoyumei1-a.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  G-TX9YHT4CS3

# SEO Related
google_site_verification :  Qe42uVU5qjnljhT-3Y4-yu3ientTVI7As7aWKo6DNnk # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   : 0E86CF30DD3F39A24F6D7994ECFC8130 # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "MEI Luoyu"
  avatar           : "images/照片_2024.jpg"
  bio              : "Joint PhD candidate at<br> City University of Hong Kong and<br> Southeast University"
  location         : "Hong Kong, Nanjing<br>⛪ City University of Hong Kong<br>🏠 Southeast University"
  googlescholar    : "https://scholar.google.com/citations?user=nOMD2YIAAAAJ"
  email            : "lymei-@seu.edu.cn"
  github           : "luoyumei1-a"
  linkedin         : "luoyu-mei-a394ab2b2"
  dblp             : "https://dblp.org/pid/301/6040.html"
  orcid            : "https://orcid.org/0000-0003-2338-0256"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
